default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.22
    hooks:
      - id: ruff-format
      - id: ruff-check

  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: v0.0.62
    hooks:
      - id: ty
